title: "Ines Hsu"
logo: "/images/Ines_github.jpg?raw=true"
description: >
  Hi, welcome to my page! I’m Ines — a strategy-driven product and operations leader passionate about transforming ideas into impactful solutions. 
  <br><br>
 
  <br><br>
  <a href="https://www.linkedin.com/in/ineshsu" target="_blank">View My LinkedIn Profile</a>

theme: jekyll-theme-minimal

show_downloads: false
google_analytics: ""  # Add your GA tracking ID if needed, e.g., "UA-XXXXXXXXX-X"
author:
  name: "Ines Hsu"
  email: "ines.kuma@gmail.com"

# Build settings
markdown: kramdown
